### ISSUE TITLE
[Bug]: Typo in "Piyushhh" on the homepage of the application

### ISSUE THREAD

**Issue by Priyanktyagi00** [Priyanktyagi00/piyushgargdev-nextjs#1]
### Describe the bug

Typo in "Piyushhh" on the homepage of the application

### To Reproduce

1. Go to 'website'
2. At the homepage
3. See error

### Expected behavior

the spelling of "Piyushhh" must be replace by "Piyush"

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by cpwallah** [comment]
hi @Priyanktyagi00  can i work on this issue
